### PR TITLE
Fix for issue #345 - Imported SAF_AGENT from model_constants and exte…

### PR DESCRIPTION
**Pull request by wszczurek**
This is my fix for issue #345.
Added importing of SAF_AGENT and use it later.
Extended __find_target method.

### CODE REVIEW

**Comment by rakillen** [comment]
With the default value for ``include_saf`` set to True, SAF agents will be allowed as targets for other elements.
I suggest you just use the existing ``include_jms`` to determine whether to invoke the SAF agent check.
That flag is only set for the SubDeployment / Target attribute through attribute_setter.set_target_jms_mbeans().
This would expand the meaning of that flag to "include targets for JMS subdeployments", which seems OK.

**Comment by wszczurek** [comment]
@ddsharpe 
I have not done it before. I have sent the signed OCA in pdf format couple of hours ago to "oracle-ca_us [at] oracle [dot] com". Hope it will be processed quickly on your side.

@rakillen 
Ok, was not sure before if I can reuse the same condition as in the chain could not find when `set_target_jms_mbeans()` is executed, as it is the only place which i could see the the `include_jms` is set to `True`.
```
[python]$ grep -rli include_jms .
./wlsdeploy/tool/util/attribute_setter.py
[python]$
```
```
[weblogic-deploy]$ grep -rli set_target_jms_mbeans .
./lib/python/wlsdeploy/tool/util/attribute_setter.py
[weblogic-deploy]$
```

I will change and test it. 
Once I will receive info from OCA - do you want me to proceed via existing Pull Request or close this one and create new one ?

**Comment by ddsharpe** [comment]
Proceed with existing.  But, you will need to tag a commit as described above.

**Comment by ddsharpe** [comment]
@wszczurek your OCA has been approved.  Please add the --signoff commit and finish your changes and testing.

**Comment by rakillen** [comment]
Regarding ```set_target_jms_mbeans()```, the public methods in ```attribute_setter.py``` are used to set attributes that can't be handled by simple data manipulation. Each is indirectly associated one or more attributes in the alias files (such as JMSSystemResource.json). That's how I determined that ```set_target_jms_mbeans``` was used in this one place, but ```set_target_mbeans``` was used a lot. Hope that helps. We are planning to improve the documentation for this.

**Comment by wszczurek** [comment]
Thanks for more information related to internals.
Definitely that would be good to have high level design and internal concept described how the tool works.

I have changed the implementation and reused the `include_jms` condition.
Signed off, squashed and pushed forcefully to my fix branch.

**Comment by rakillen** [comment]
Fixes #345

**Pull request merged**
