### PR TITLE
fix: typo grammar spell

### PR DESCRIPTION
**Pull request by slowy07**
fix typo grammar spelling, and replace with to correct word with reference from [Merriam webster](https://www.merriam-webster.com/)

### CODE REVIEW

**Comment by ddsharpe** [comment]
@slowy07 Thank you for your interest in helping us with our project.  Unfortunately in its current form, I cannot accept this pull request.  Please follow the guidelines for contributing (and most Oracle projects) at the root of this project at https://github.com/oracle/weblogic-deploy-tooling/blob/main/CONTRIBUTING.md.

**Comment by slowy07** [comment]
thanks sir @ddsharpe , i sign in on [OCA](https://oca.opensource.oracle.com/) website, and my agreement under review, so, i create commit message with my name and email right ??

**Comment by ddsharpe** [comment]
> thanks sir @ddsharpe , i sign in on [OCA](https://oca.opensource.oracle.com/) website, and my agreement under review, so, i create commit message with my name and email right ??

@slowy07 Yes, and the commit must be "signed" using `git commit --signoff`

**Comment by slowy07** [comment]
sorry sir @ddsharpe , i commit use ``git commit signed of by : name <email@example.org>`` 😂, i fix that

**Comment by ddsharpe** [comment]
Yes, that looks correct.  We just need the OCA to be approved.  Thank you.

**Comment by slowy07** [comment]
thank you sir @ddsharpe

**Comment by ddsharpe** [comment]
OCA was approved and posted to https://oca.opensource.oracle.com/?ojr=contrib-list

**Review by ddsharpe — APPROVED** [review]

**Review by rakillen — APPROVED** [review]

**Pull request merged**
